### PR TITLE
Switch to mongoclient

### PR DESCRIPTION
**Pull request by GuusH**
Switched the way this module talks to MongoDB from Connection to MongoClient. Tested with pymongo 2.6.2 and 3.0.1 against MongoDB 2.6.9

### CODE REVIEW

**Comment by naparuba** [comment]
Thanks, 4Ill give a try and merge it ^^

**Comment by mohierf** [comment]
@naparuba : I also need this PR and I think it will be really necessary nowadays ... pymongo must be at least version 3 for MongoDB version 3 ... if you want I may merge, test and publish a new version of this module ?

**Comment by gst** [comment]
let's merge.

**Comment by mohierf** [comment]
:+1: for you @gst ! But I think only @naparuba can publish on shinken.io ...

**Comment by cellcore** [comment]
Any update on this getting pushed to shinken.io?

**Comment by nawadanp** [comment]
Hi here,
Any news from @naparuba about updating shinken.io ?
Thanks !

**Comment by david-guenault** [comment]
huge change in pymongo 3. See this http://stackoverflow.com/questions/31240952/pymongo-3-0-3-importerror-no-module-named-connection

**Pull request merged**
