### PR TITLE
Add support for MongoDB authentication

### PR DESCRIPTION
**Pull request by ryanbsaunders**
These changes add support for username/password authentication against a MongoDB server with authentication enabled.   Authentication is required in my production environment. (and I'm sure the same is true for many others as well)

### CODE REVIEW

**Comment by ryanbsaunders** [comment]
This PR has been sitting unacknowledged for some time.  It would be wonderful if I could get some feedback on the changes.

**Comment by olivierHa** [comment]
Sorry the delay.

**Comment by bittrance** [comment]
I would suggest going for #12 instead which provides mongodb 3 support that uses URIs which solves this issue as well.

**Comment by ryanbsaunders** [comment]
We're not using mongodb3 in my environment yet, so that doesn't help with older versions.  Though I would rather use a URI.

What will it take to get a new release including this authentication @olivierHa?  I'd like to install the module using 'shinken install'.

**Pull request merged**
