### PR TITLE
Improve pymongo usage

### PR DESCRIPTION
**Pull request by bittrance**
This PR does three things:
1) Pull andrewmcgilvray's upsert implementation
2) log exceptions in worker processes
3) compatible with pymongo 3.2

### CODE REVIEW

**Comment by lchabert** [comment]
Hi,

I have make some test with this plugin version, and no issue to report with mongo3.2.
Someone can merge this PR ?

Thanks in advance,
Regards.

**Comment by olivierHa** [comment]
Hello,  This is merged. 

I think we need to add a minimum supported pymongo version library.
Which minimum pymongo is required to use this module ? I would say 2.9 is a good candidate.

Regards

Olivier

**Comment by lchabert** [comment]
Hello,

Thanks for merge.

Bulk operation has been added in pymongo 2.7.
2.7 support also login and rs with url.

2.7 is minimal version required ?

Regards.

**Comment by olivierHa** [comment]
According to this :
https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-python

2.7 isn't compatible with Mongo3.

With pymongo 2.9 as a requirement , I think we are more "safe" about
bugs/issues that we can encounter.

https://docs.mongodb.com/ecosystem/drivers/python/ says that it is even
compatible with Mongo3.2

But I have no feedback on that.



2016-08-02 15:17 GMT+02:00 Chabert Loïc <notifications@github.com>:

**Comment by lchabert** [comment]
Pymongo 2.9 is a safe choice. Do you need test with this version ?

**Pull request merged**
